### ISSUE TITLE
Transform the new entities tables into a text box where authors can upload entities one per line

### ISSUE THREAD

**Issue by valearna** [WormBase/author-first-pass#193] opened 2021-04-16 18:58 UTC
Load a text file

**Comment by draciti** [comment] 2021-05-14 20:10
works well, data correctly saved in postgres

**Comment by vanaukenk** [comment] 2021-08-20 15:08
Also reopening this ticket as we may want to make some modifications as a result of v3 testing.

**Comment by draciti** [comment] 2021-08-20 18:55
duplicate of #203

**Closed by draciti** 2021-08-20 18:55 UTC
