### ISSUE TITLE
email to author for WBPaper00059764 has problems

### ISSUE THREAD

**Issue by draciti** [WormBase/author-first-pass#216] opened 2021-08-23 13:05 UTC
From Sander van den Heuvel
Dear Wormbase,
Could you please check on the message below, there’s no paper title indicated and the majority of genes listed seem unrelated to our studies,
Thanks and best wishes,
Sander

Message received by the  author:
Dear Author,

We recently sent an email asking for your help in flagging entities and data types for WormBase curation for the
recently published paper:

"", 

We would like to remind you that it is still possible to submit your response by visiting the Author First Pass Form for your paper

If you have started on the form, but not finished, you may resume your submission to complete the process.

If you have questions about completing the form, please feel free to reply to this email and we will be happy to assist
you. 

Thank you for helping WormBase!

**Comment by valearna** [comment] 2021-08-23 15:46
It seems that all pap_ tables for WBPaper00059764 on tazendra are empty. I can see the old values on mangolassi, so they must have been deleted recently. Can we trace the history of this paper from the paper editor @vanaukenk ? Maybe it is a duplicate of another paper ID?

**Comment by vanaukenk** [comment] 2021-08-23 15:53
@valearna 
WBPaper00059764 was merged into WBPaper00060275 on July 27th since they were duplicates.
WBPaper00060275 was processed back in December and it looks like it was submitted for AFP.
I've had to do some paper merges lately for cleaning up our Alliance submission.
Most of them were older papers, but perhaps we should double-check to see if any other now invalid papers went through AFP?

**Comment by valearna** [comment] 2021-08-23 15:56
Ok, thanks. That explains it @vanaukenk. Yes, I can delete the AFP entries of papers that have been merged into different pap IDs. Is there a special flag I should look for in postgres?

**Comment by vanaukenk** [comment] 2021-08-23 16:06
@valearna 
The pap_identifier table contains merged paper ids in the form of an 8-digit number without a prefix, for example '00059764'.
The numbers would start with at least three zeros.  
The merged paper entry in the pap_identifier table should also have pap_status value 'invalid'.

Please let me know if you need more info.  Thx.

**Comment by azurebrd** [comment] 2021-08-23 16:18
@valearna @vanaukenk I imagine the last check is the important one, assuming you never want to send messages to authors of invalid papers.  If all merged papers become invalid, there shouldn't be a need to check the pap_identifier tables.

**Comment by vanaukenk** [comment] 2021-08-23 18:39
From the original comment in this ticket, it looks like we sent a reminder email to the author after the paper in question was merged and made invalid.
I don't think this exact scenario will happen often, but maybe including a routine check for now invalid papers in the AFP system would be a good safety net.

**Comment by valearna** [comment] 2021-08-23 18:43
I agree with you @vanaukenk. We can skip merged papers when sending out reminder emails. We should also discuss how to manage cases where an author clicks on an old link related to a paper that has been merged in the meanwhile. This shouldn't happen often, but maybe we could show a page where we say that the paper has been merged.

**Comment by draciti** [comment] 2021-08-23 18:59
Thanks, all, for looking into this.
I will let the author know. It seems he already filled out the AFP request for 00060275 
https://dashboard.afp.textpressolab.com/paper?paper_id=00060275

**Comment by valearna** [comment] 2021-08-30 22:33
Is there any additional work to be done related to this issue @vanaukenk @draciti ?

**Closed** 2021-09-03 19:04 UTC
